version: '3'

services:
  registry:
    container_name: registry-caixa
    image: registry
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /opt/data:/data
